# Version of the docker-composer syntax to use 
version: "3.9"

services: 
  app:
    # Build the docker file inside our current directory 
    build:
      context: .
      args:
        - DEV=true
    # Map the port 8000 inside this machine to port 8000 inside our docker container
    ports:
      - "8000:8000"
    # Map the app directory to the app directory inside the container (this is so the changes done in the code are reflected in the container in real time)
    volumes:
      - .app/:/app
    # Command used to run the service
    command:
      sh -c "python manage.py runserver 0.0.0.0:8000"